/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorefrontRouteImport } from './routes/_storefront'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as StorefrontWishlistRouteImport } from './routes/_storefront/wishlist'
import { Route as StorefrontShopRouteImport } from './routes/_storefront/shop'
import { Route as StorefrontSearchRouteImport } from './routes/_storefront/search'
import { Route as StorefrontRegionsRouteImport } from './routes/_storefront/regions'
import { Route as StorefrontProfileRouteImport } from './routes/_storefront/profile'
import { Route as StorefrontProductRouteImport } from './routes/_storefront/product'
import { Route as StorefrontOrdersRouteImport } from './routes/_storefront/orders'
import { Route as StorefrontOrderSuccessRouteImport } from './routes/_storefront/order-success'
import { Route as StorefrontOcopMapRouteImport } from './routes/_storefront/ocop-map'
import { Route as StorefrontCheckoutRouteImport } from './routes/_storefront/checkout'
import { Route as StorefrontCategoryRouteImport } from './routes/_storefront/category'
import { Route as StorefrontCartRouteImport } from './routes/_storefront/cart'
import { Route as StorefrontShopShopIdRouteImport } from './routes/_storefront/shop.$shopId'
import { Route as StorefrontSellerRegisterRouteImport } from './routes/_storefront/seller.register'
import { Route as StorefrontSellerProductsRouteImport } from './routes/_storefront/seller.products'
import { Route as StorefrontSellerDashboardRouteImport } from './routes/_storefront/seller.dashboard'
import { Route as StorefrontRegionsRegionSlugRouteImport } from './routes/_storefront/regions.$regionSlug'
import { Route as StorefrontProductProductIdRouteImport } from './routes/_storefront/product.$productId'
import { Route as StorefrontCategorySlugRouteImport } from './routes/_storefront/category.$slug'
import { Route as StorefrontAccountRegisterRouteImport } from './routes/_storefront/account/register'
import { Route as StorefrontAccountLoginRouteImport } from './routes/_storefront/account/login'

const StorefrontRoute = StorefrontRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontWishlistRoute = StorefrontWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontShopRoute = StorefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontSearchRoute = StorefrontSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontRegionsRoute = StorefrontRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontProfileRoute = StorefrontProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontProductRoute = StorefrontProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontOrdersRoute = StorefrontOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontOrderSuccessRoute = StorefrontOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontOcopMapRoute = StorefrontOcopMapRouteImport.update({
  id: '/ocop-map',
  path: '/ocop-map',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCheckoutRoute = StorefrontCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCategoryRoute = StorefrontCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCartRoute = StorefrontCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontShopShopIdRoute = StorefrontShopShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => StorefrontShopRoute,
} as any)
const StorefrontSellerRegisterRoute =
  StorefrontSellerRegisterRouteImport.update({
    id: '/seller/register',
    path: '/seller/register',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontSellerProductsRoute =
  StorefrontSellerProductsRouteImport.update({
    id: '/seller/products',
    path: '/seller/products',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontSellerDashboardRoute =
  StorefrontSellerDashboardRouteImport.update({
    id: '/seller/dashboard',
    path: '/seller/dashboard',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontRegionsRegionSlugRoute =
  StorefrontRegionsRegionSlugRouteImport.update({
    id: '/$regionSlug',
    path: '/$regionSlug',
    getParentRoute: () => StorefrontRegionsRoute,
  } as any)
const StorefrontProductProductIdRoute =
  StorefrontProductProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => StorefrontProductRoute,
  } as any)
const StorefrontCategorySlugRoute = StorefrontCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StorefrontCategoryRoute,
} as any)
const StorefrontAccountRegisterRoute =
  StorefrontAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontAccountLoginRoute = StorefrontAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => StorefrontRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/cart': typeof StorefrontCartRoute
  '/category': typeof StorefrontCategoryRouteWithChildren
  '/checkout': typeof StorefrontCheckoutRoute
  '/ocop-map': typeof StorefrontOcopMapRoute
  '/order-success': typeof StorefrontOrderSuccessRoute
  '/orders': typeof StorefrontOrdersRoute
  '/product': typeof StorefrontProductRouteWithChildren
  '/profile': typeof StorefrontProfileRoute
  '/regions': typeof StorefrontRegionsRouteWithChildren
  '/search': typeof StorefrontSearchRoute
  '/shop': typeof StorefrontShopRouteWithChildren
  '/wishlist': typeof StorefrontWishlistRoute
  '/account/login': typeof StorefrontAccountLoginRoute
  '/account/register': typeof StorefrontAccountRegisterRoute
  '/category/$slug': typeof StorefrontCategorySlugRoute
  '/product/$productId': typeof StorefrontProductProductIdRoute
  '/regions/$regionSlug': typeof StorefrontRegionsRegionSlugRoute
  '/seller/dashboard': typeof StorefrontSellerDashboardRoute
  '/seller/products': typeof StorefrontSellerProductsRoute
  '/seller/register': typeof StorefrontSellerRegisterRoute
  '/shop/$shopId': typeof StorefrontShopShopIdRoute
}
export interface FileRoutesByTo {
  '/cart': typeof StorefrontCartRoute
  '/category': typeof StorefrontCategoryRouteWithChildren
  '/checkout': typeof StorefrontCheckoutRoute
  '/ocop-map': typeof StorefrontOcopMapRoute
  '/order-success': typeof StorefrontOrderSuccessRoute
  '/orders': typeof StorefrontOrdersRoute
  '/product': typeof StorefrontProductRouteWithChildren
  '/profile': typeof StorefrontProfileRoute
  '/regions': typeof StorefrontRegionsRouteWithChildren
  '/search': typeof StorefrontSearchRoute
  '/shop': typeof StorefrontShopRouteWithChildren
  '/wishlist': typeof StorefrontWishlistRoute
  '/': typeof StorefrontIndexRoute
  '/account/login': typeof StorefrontAccountLoginRoute
  '/account/register': typeof StorefrontAccountRegisterRoute
  '/category/$slug': typeof StorefrontCategorySlugRoute
  '/product/$productId': typeof StorefrontProductProductIdRoute
  '/regions/$regionSlug': typeof StorefrontRegionsRegionSlugRoute
  '/seller/dashboard': typeof StorefrontSellerDashboardRoute
  '/seller/products': typeof StorefrontSellerProductsRoute
  '/seller/register': typeof StorefrontSellerRegisterRoute
  '/shop/$shopId': typeof StorefrontShopShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_storefront': typeof StorefrontRouteWithChildren
  '/_storefront/cart': typeof StorefrontCartRoute
  '/_storefront/category': typeof StorefrontCategoryRouteWithChildren
  '/_storefront/checkout': typeof StorefrontCheckoutRoute
  '/_storefront/ocop-map': typeof StorefrontOcopMapRoute
  '/_storefront/order-success': typeof StorefrontOrderSuccessRoute
  '/_storefront/orders': typeof StorefrontOrdersRoute
  '/_storefront/product': typeof StorefrontProductRouteWithChildren
  '/_storefront/profile': typeof StorefrontProfileRoute
  '/_storefront/regions': typeof StorefrontRegionsRouteWithChildren
  '/_storefront/search': typeof StorefrontSearchRoute
  '/_storefront/shop': typeof StorefrontShopRouteWithChildren
  '/_storefront/wishlist': typeof StorefrontWishlistRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/_storefront/account/login': typeof StorefrontAccountLoginRoute
  '/_storefront/account/register': typeof StorefrontAccountRegisterRoute
  '/_storefront/category/$slug': typeof StorefrontCategorySlugRoute
  '/_storefront/product/$productId': typeof StorefrontProductProductIdRoute
  '/_storefront/regions/$regionSlug': typeof StorefrontRegionsRegionSlugRoute
  '/_storefront/seller/dashboard': typeof StorefrontSellerDashboardRoute
  '/_storefront/seller/products': typeof StorefrontSellerProductsRoute
  '/_storefront/seller/register': typeof StorefrontSellerRegisterRoute
  '/_storefront/shop/$shopId': typeof StorefrontShopShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/ocop-map'
    | '/order-success'
    | '/orders'
    | '/product'
    | '/profile'
    | '/regions'
    | '/search'
    | '/shop'
    | '/wishlist'
    | '/account/login'
    | '/account/register'
    | '/category/$slug'
    | '/product/$productId'
    | '/regions/$regionSlug'
    | '/seller/dashboard'
    | '/seller/products'
    | '/seller/register'
    | '/shop/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/category'
    | '/checkout'
    | '/ocop-map'
    | '/order-success'
    | '/orders'
    | '/product'
    | '/profile'
    | '/regions'
    | '/search'
    | '/shop'
    | '/wishlist'
    | '/'
    | '/account/login'
    | '/account/register'
    | '/category/$slug'
    | '/product/$productId'
    | '/regions/$regionSlug'
    | '/seller/dashboard'
    | '/seller/products'
    | '/seller/register'
    | '/shop/$shopId'
  id:
    | '__root__'
    | '/_storefront'
    | '/_storefront/cart'
    | '/_storefront/category'
    | '/_storefront/checkout'
    | '/_storefront/ocop-map'
    | '/_storefront/order-success'
    | '/_storefront/orders'
    | '/_storefront/product'
    | '/_storefront/profile'
    | '/_storefront/regions'
    | '/_storefront/search'
    | '/_storefront/shop'
    | '/_storefront/wishlist'
    | '/_storefront/'
    | '/_storefront/account/login'
    | '/_storefront/account/register'
    | '/_storefront/category/$slug'
    | '/_storefront/product/$productId'
    | '/_storefront/regions/$regionSlug'
    | '/_storefront/seller/dashboard'
    | '/_storefront/seller/products'
    | '/_storefront/seller/register'
    | '/_storefront/shop/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StorefrontRoute: typeof StorefrontRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/wishlist': {
      id: '/_storefront/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StorefrontWishlistRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/shop': {
      id: '/_storefront/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StorefrontShopRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/search': {
      id: '/_storefront/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof StorefrontSearchRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/regions': {
      id: '/_storefront/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof StorefrontRegionsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/profile': {
      id: '/_storefront/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StorefrontProfileRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/product': {
      id: '/_storefront/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof StorefrontProductRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/orders': {
      id: '/_storefront/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof StorefrontOrdersRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/order-success': {
      id: '/_storefront/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof StorefrontOrderSuccessRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/ocop-map': {
      id: '/_storefront/ocop-map'
      path: '/ocop-map'
      fullPath: '/ocop-map'
      preLoaderRoute: typeof StorefrontOcopMapRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/category': {
      id: '/_storefront/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof StorefrontCategoryRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/cart': {
      id: '/_storefront/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StorefrontCartRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/shop/$shopId': {
      id: '/_storefront/shop/$shopId'
      path: '/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof StorefrontShopShopIdRouteImport
      parentRoute: typeof StorefrontShopRoute
    }
    '/_storefront/seller/register': {
      id: '/_storefront/seller/register'
      path: '/seller/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof StorefrontSellerRegisterRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/seller/products': {
      id: '/_storefront/seller/products'
      path: '/seller/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof StorefrontSellerProductsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/seller/dashboard': {
      id: '/_storefront/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof StorefrontSellerDashboardRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/regions/$regionSlug': {
      id: '/_storefront/regions/$regionSlug'
      path: '/$regionSlug'
      fullPath: '/regions/$regionSlug'
      preLoaderRoute: typeof StorefrontRegionsRegionSlugRouteImport
      parentRoute: typeof StorefrontRegionsRoute
    }
    '/_storefront/product/$productId': {
      id: '/_storefront/product/$productId'
      path: '/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof StorefrontProductProductIdRouteImport
      parentRoute: typeof StorefrontProductRoute
    }
    '/_storefront/category/$slug': {
      id: '/_storefront/category/$slug'
      path: '/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof StorefrontCategorySlugRouteImport
      parentRoute: typeof StorefrontCategoryRoute
    }
    '/_storefront/account/register': {
      id: '/_storefront/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof StorefrontAccountRegisterRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/account/login': {
      id: '/_storefront/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof StorefrontAccountLoginRouteImport
      parentRoute: typeof StorefrontRoute
    }
  }
}

interface StorefrontCategoryRouteChildren {
  StorefrontCategorySlugRoute: typeof StorefrontCategorySlugRoute
}

const StorefrontCategoryRouteChildren: StorefrontCategoryRouteChildren = {
  StorefrontCategorySlugRoute: StorefrontCategorySlugRoute,
}

const StorefrontCategoryRouteWithChildren =
  StorefrontCategoryRoute._addFileChildren(StorefrontCategoryRouteChildren)

interface StorefrontProductRouteChildren {
  StorefrontProductProductIdRoute: typeof StorefrontProductProductIdRoute
}

const StorefrontProductRouteChildren: StorefrontProductRouteChildren = {
  StorefrontProductProductIdRoute: StorefrontProductProductIdRoute,
}

const StorefrontProductRouteWithChildren =
  StorefrontProductRoute._addFileChildren(StorefrontProductRouteChildren)

interface StorefrontRegionsRouteChildren {
  StorefrontRegionsRegionSlugRoute: typeof StorefrontRegionsRegionSlugRoute
}

const StorefrontRegionsRouteChildren: StorefrontRegionsRouteChildren = {
  StorefrontRegionsRegionSlugRoute: StorefrontRegionsRegionSlugRoute,
}

const StorefrontRegionsRouteWithChildren =
  StorefrontRegionsRoute._addFileChildren(StorefrontRegionsRouteChildren)

interface StorefrontShopRouteChildren {
  StorefrontShopShopIdRoute: typeof StorefrontShopShopIdRoute
}

const StorefrontShopRouteChildren: StorefrontShopRouteChildren = {
  StorefrontShopShopIdRoute: StorefrontShopShopIdRoute,
}

const StorefrontShopRouteWithChildren = StorefrontShopRoute._addFileChildren(
  StorefrontShopRouteChildren,
)

interface StorefrontRouteChildren {
  StorefrontCartRoute: typeof StorefrontCartRoute
  StorefrontCategoryRoute: typeof StorefrontCategoryRouteWithChildren
  StorefrontCheckoutRoute: typeof StorefrontCheckoutRoute
  StorefrontOcopMapRoute: typeof StorefrontOcopMapRoute
  StorefrontOrderSuccessRoute: typeof StorefrontOrderSuccessRoute
  StorefrontOrdersRoute: typeof StorefrontOrdersRoute
  StorefrontProductRoute: typeof StorefrontProductRouteWithChildren
  StorefrontProfileRoute: typeof StorefrontProfileRoute
  StorefrontRegionsRoute: typeof StorefrontRegionsRouteWithChildren
  StorefrontSearchRoute: typeof StorefrontSearchRoute
  StorefrontShopRoute: typeof StorefrontShopRouteWithChildren
  StorefrontWishlistRoute: typeof StorefrontWishlistRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontAccountLoginRoute: typeof StorefrontAccountLoginRoute
  StorefrontAccountRegisterRoute: typeof StorefrontAccountRegisterRoute
  StorefrontSellerDashboardRoute: typeof StorefrontSellerDashboardRoute
  StorefrontSellerProductsRoute: typeof StorefrontSellerProductsRoute
  StorefrontSellerRegisterRoute: typeof StorefrontSellerRegisterRoute
}

const StorefrontRouteChildren: StorefrontRouteChildren = {
  StorefrontCartRoute: StorefrontCartRoute,
  StorefrontCategoryRoute: StorefrontCategoryRouteWithChildren,
  StorefrontCheckoutRoute: StorefrontCheckoutRoute,
  StorefrontOcopMapRoute: StorefrontOcopMapRoute,
  StorefrontOrderSuccessRoute: StorefrontOrderSuccessRoute,
  StorefrontOrdersRoute: StorefrontOrdersRoute,
  StorefrontProductRoute: StorefrontProductRouteWithChildren,
  StorefrontProfileRoute: StorefrontProfileRoute,
  StorefrontRegionsRoute: StorefrontRegionsRouteWithChildren,
  StorefrontSearchRoute: StorefrontSearchRoute,
  StorefrontShopRoute: StorefrontShopRouteWithChildren,
  StorefrontWishlistRoute: StorefrontWishlistRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontAccountLoginRoute: StorefrontAccountLoginRoute,
  StorefrontAccountRegisterRoute: StorefrontAccountRegisterRoute,
  StorefrontSellerDashboardRoute: StorefrontSellerDashboardRoute,
  StorefrontSellerProductsRoute: StorefrontSellerProductsRoute,
  StorefrontSellerRegisterRoute: StorefrontSellerRegisterRoute,
}

const StorefrontRouteWithChildren = StorefrontRoute._addFileChildren(
  StorefrontRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StorefrontRoute: StorefrontRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
